### ISSUE TITLE
Is r8 for reverse really solvable?

### ISSUE THREAD

**Issue by jeffli678** [wapiflapi/exrs#5]
Thanks for the collection of the challenges! I have completed all the reversing challenges except for r8. Upon closer inspection I think its not solvable. Details are below: 

I have reversed the code and understand its logic. So the problem is the MD5. We know its not satisfiable (or more precisely, virtually impossible to find an input that satisfies the constraint). So I guess its probably related to some integer overflow trick. However, since the program checks to make sure the last but one input cannot be zero, the rounds of the MD5 calculation cannot be 0 (and its positive, too). Which makes overflow impossible.

Please double-check. If I am wrong, please also post a working input so I can see how I missed it.

**Comment by wapiflapi** [comment]
I have solved it. People in #1 claim to have solved it. I don't see a reason it wouldn't be solvable anymore.

I don't post solutions or walk-throughs, this is not a tutorial and i don't feel like writing one :-) honestly this is years old and I don't even remember it. Though feel free to write one if you think it'll help people! I know there's some good walk-throughs on YouTube, other githubs and blog posts. Not sure if they're for this particular challenge.

Good luck!

**Comment by jeffli678** [comment]
Thanks for your quick response! 

I noticed that someone in #1 mentions he solves it. I am hesitant, but I still think there is a problem with the challenge. I mean there could be particular inputs that satisfies the constraint, but it cannot be found without brute-forcing lots of possibilities. 

I will double-check too. 

r9 seems the best one so far and maybe I will use it for an intro to z3, angr, klee, etc. I will let you know if its picked.

**Comment by jeffli678** [comment]
Update: with some help I finally solved it. r8 is the best among all rev challs. It is so covert that even I noticed the correct place for the trick, I still missed it. Thanks for the challenge!
