### ISSUE TITLE
S3 in sploit section

### ISSUE THREAD

**Issue by muhammetozendev** [wapiflapi/exrs#6]
Is there any solution page available? I'm stuck in s3

**Comment by wapiflapi** [comment]
I do not provided a he challenges not the solution. However i know some
people have written write ups for some of them so if you look around the
internet you might find something.

Learning more about how the stack and function calls work in x86 might hell
you if you're stuck. The challenges were designed to introduce as few new
things as possible on each level.

Good luck!
